version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgres-lms
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lmsdb
    volumes:
      - postgres_data:/var/lib/docker/volumes/postgres_volume/data
    networks:
      - app-network


  spring-boot-app:
    image: lms-app:1.0
    build: ./
    container_name: springboot-lms
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL:jdbc:postgressql://postgres-lms:5432:/lmsdb
      - SPRING_DATASOURCE_USERNAME:postgres
      - SPRING_DATASOURCE_PASSWORD:postgres

    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

